"""empty message

Revision ID: 983146022417
Revises: bf955c32d6ad
Create Date: 2020-05-16 23:38:55.198283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '983146022417'
down_revision = 'bf955c32d6ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('address', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artists', 'address')
    # ### end Alembic commands ###
