"""empty message

Revision ID: a03208402a3c
Revises: 983146022417
Create Date: 2020-05-16 23:41:46.092383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a03208402a3c'
down_revision = '983146022417'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artists', 'website')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('website', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
